<?php

namespace Frigg\FlightBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FlightStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightStatusRepository extends EntityRepository
{
}
