frigg_flight_rest:
    type: rest
    prefix: /api
    resource: "@FriggFlightBundle/Resources/config/routing.yml"

frigg_flight_web:
    resource: "@FriggFlightBundle/Controller"
    type: annotation