parameters:
    frigg_fly.flight_import.class: Frigg\FlyBundle\Import\FlightImport
    frigg_fly.flight_import.config: "%kernel.root_dir%/../src/Frigg/FlyBundle/Resources/config/import/flight.yml"
    frigg_fly.flight_status_import.class: Frigg\FlyBundle\Import\FlightStatusImport
    frigg_fly.flight_status_import.config: "%kernel.root_dir%/../src/Frigg/FlyBundle/Resources/config/import/flight_status.yml"
    frigg_fly.airport_import.class: Frigg\FlyBundle\Import\AirportImport
    frigg_fly.airport_import.config: "%kernel.root_dir%/../src/Frigg/FlyBundle/Resources/config/import/airport.yml"
    frigg_fly.airline_import.class: Frigg\FlyBundle\Import\AirlineImport
    frigg_fly.airline_import.config: "%kernel.root_dir%/../src/Frigg/FlyBundle/Resources/config/import/airline.yml"

services:
    frigg_fly.flight_import:
        class: %frigg_fly.flight_import.class%
        arguments: [ @service_container, %frigg_fly.flight_import.config%  ]

    frigg_fly.flight_status_import:
        class: %frigg_fly.flight_status_import.class%
        arguments: [ @service_container, %frigg_fly.flight_status_import.config%  ]

    frigg_fly.airport_import:
        class: %frigg_fly.airport_import.class%
        arguments: [ @service_container, %frigg_fly.airport_import.config%  ]

    frigg_fly.airline_import:
        class: %frigg_fly.airline_import.class%
        arguments: [ @service_container, %frigg_fly.airline_import.config%  ]
