default: 1119 # OSL
import:
    #endpoint: http://flydata.avinor.no/airportNames.asp
    endpoint: data/airportNames.asp.xml
    avinor:
        - ALF
        - ANX
        - BDU
        - BGO
        - BVG
        - BOO
        - BNN
        - BJF
        - VDB
        - FRO
        - FDE
        - HFT
        - EVE
        - HAA
        - HAU
        - HVG
        - KKN
        - KRS
        - KSU
        - LKL
        - LKN
        - MEH
        - MQN
        - MOL
        - MJF
        - OSY
        - NVK
        - OSL
        - RRS
        - RVK
        - RET
        - SDN
        - SSJ
        - SOG
        - SVG
        - SKN
        - LYR
        - SVJ
        - SOJ
        - TOS
        - TRD
        - VDS
        - VAW
        - VRY
        - HOV
        - AES
