airport:
    type: rest
    resource: Frigg\FlightBundle\Controller\Rest\AirportController

airport_flight:
    type: rest
    resource: Frigg\FlightBundle\Controller\Rest\AirportFlightController

airline:
    type: rest
    resource: Frigg\FlightBundle\Controller\Rest\AirlineController

airline_flight:
    type: rest
    resource: Frigg\FlightBundle\Controller\Rest\AirlineFlightController
