airport:
    type: rest
    resource: Frigg\FlightBundle\Controller\API\AirportController

airport_flight:
    type: rest
    resource: Frigg\FlightBundle\Controller\API\AirportFlightController

airline:
    type: rest
    resource: Frigg\FlightBundle\Controller\API\AirlineController

airline_flight:
    type: rest
    resource: Frigg\FlightBundle\Controller\API\AirlineFlightController
