parameters:
    # Flight settings
    frigg.flight.config.file: "%kernel.root_dir%/../src/Frigg/FlightBundle/Resources/config/FriggFlight/flight.yml"
    frigg.flight.import.class: Frigg\FlightBundle\Import\FlightImportService

    # Status settings
    frigg.status.config.file: "%kernel.root_dir%/../src/Frigg/FlightBundle/Resources/config/FriggFlight/status.yml"
    frigg.status.import.class: Frigg\FlightBundle\Import\StatusImportService

    # Airport settings
    frigg.airport.config.file: "%kernel.root_dir%/../src/Frigg/FlightBundle/Resources/config/FriggFlight/airport.yml"
    frigg.airport.import.class: Frigg\FlightBundle\Import\AirportImportService
    frigg.airport.flight.class: Frigg\FlightBundle\Service\AirportFlightService

    # Airline settings
    frigg.airline.config.file: "%kernel.root_dir%/../src/Frigg/FlightBundle/Resources/config/FriggFlight/airline.yml"
    frigg.airline.import.class: Frigg\FlightBundle\Import\AirlineImportService
    frigg.airline.flight.class: Frigg\FlightBundle\Service\AirlineFlightService

services:
    # Importer services
    frigg.flight.import:
        class: %frigg.flight.import.class%
        arguments: [ @service_container, %frigg.flight.config.file% ]

    frigg.status.import:
        class: %frigg.status.import.class%
        arguments: [ @service_container, %frigg.status.config.file%  ]

    frigg.airport.import:
        class: %frigg.airport.import.class%
        arguments: [ @service_container, %frigg.airport.config.file%  ]

    frigg.airline.import:
        class: %frigg.airline.import.class%
        arguments: [ @service_container, %frigg.airline.config.file%  ]

    # Flight services
    frigg.airport.flight:
        class: %frigg.airport.flight.class%
        arguments: [ @doctrine.orm.entity_manager, @session, %frigg.airport.config.file% ]

    frigg.airline.flight:
        class: %frigg.airline.flight.class%
        arguments: [ @doctrine.orm.entity_manager, @session, %frigg.airline.config.file% ]
